name = "mymed-health"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXTAUTH_URL = "https://mymed.health"
NEXTAUTH_SECRET = "your-nextauth-secret-here-generate-with-openssl-rand-base64-32"
GOOGLE_CLIENT_ID = "97284588200-gi7nuf3mordd1mg821pc9fvlqdftfq1k.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

# For production deployment, update this with your domain
# [env.production]
# routes = [
#   { pattern = "/*", zone_name = "yourdomain.com" }
# ]

[[d1_databases]]
binding = "DB" # This is the name that will be available in your code
database_name = "ssn_production" # This is the name of your D1 database
database_id = "b95dba43-ff33-4935-8ff0-dd8590befb5d" # Replace with your actual database ID
migrations_table = "migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations" # Specify your custom migration directory